version: "3"
# this file uses prebuilt image in dockerhub
# https://hub.docker.com/repository/docker/canhminhdo/maude-3.5/
services:
  code:
    image: canhminhdo/maude-3.5
    working_dir: /code
    volumes:
      - ./:/code
    stdin_open: true
    tty: true
    mem_limit: 2G